// <auto-generated />
using EggIncognito.Data.Services;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace EggIncognito.Data.Migrations
{
    [DbContext(typeof(EggIncognitoDbContext))]
    [Migration("20260926190000_DropVirtualDeviceTables")]
    partial class DropVirtualDeviceTables
    {
    }
}
