// <auto-generated />
using System;
using EggIncognito.Data.Services;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EggIncognito.Data.Migrations
{
    [DbContext(typeof(EggIncognitoDbContext))]
    partial class EggIncognitoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EggIncognito.Data.Models.AnalyzedFile", b =>
                {
                    b.Property<string>("FileSha")
                        .HasColumnType("text")
                        .HasColumnName("file_sha");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("client_version");

                    b.Property<string>("FileName")
                        .HasColumnType("text")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("ProtoSha")
                        .HasColumnType("text")
                        .HasColumnName("proto_sha");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("FileSha");

                    b.HasIndex("FirstSeen");

                    b.ToTable("analyzed_files");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key_hash");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_used_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("prefix");

                    b.Property<long>("RequestCount")
                        .HasColumnType("bigint")
                        .HasColumnName("request_count");

                    b.Property<bool>("Revoked")
                        .HasColumnType("boolean")
                        .HasColumnName("revoked");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revoked_at");

                    b.HasKey("Id");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("OwnerUserId");

                    b.ToTable("api_keys");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.AppSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("app_settings", null, t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ArtifactConsumeObservation", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("action");

                    b.Property<string>("Byproducts")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("byproducts")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("client_version");

                    b.Property<int>("CountRequested")
                        .HasColumnType("integer")
                        .HasColumnName("count_requested");

                    b.Property<int?>("CraftingCount")
                        .HasColumnType("integer")
                        .HasColumnName("crafting_count");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<double?>("GoldPricePaid")
                        .HasColumnType("double precision")
                        .HasColumnName("gold_price_paid");

                    b.Property<double>("GoldenEggs")
                        .HasColumnType("double precision")
                        .HasColumnName("golden_eggs");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("OtherRewards")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("other_rewards")
                        .HasDefaultValueSql("'[]'");

                    b.Property<string>("RarityAchieved")
                        .HasColumnType("text")
                        .HasColumnName("rarity_achieved");

                    b.Property<string>("SpecLevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_level");

                    b.Property<string>("SpecName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_name");

                    b.Property<string>("SpecRarity")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec_rarity");

                    b.Property<bool>("Success")
                        .HasColumnType("boolean")
                        .HasColumnName("success");

                    b.HasKey("Id");

                    b.HasIndex("SpecName", "SpecLevel", "SpecRarity", "Action");

                    b.ToTable("artifact_consume_observations");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.BackfillJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<int>("Imported")
                        .HasColumnType("integer")
                        .HasColumnName("imported");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("StartedBy")
                        .HasColumnType("text")
                        .HasColumnName("started_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int?>("Total")
                        .HasColumnType("integer")
                        .HasColumnName("total");

                    b.HasKey("Id");

                    b.HasIndex("Source", "StartedAt");

                    b.ToTable("backfill_jobs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.BuildBlob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.HasIndex("Sha256");

                    b.ToTable("build_blobs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.CaptureProxyAddr", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("Addr")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("addr");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.HasKey("UserId");

                    b.HasIndex("Addr")
                        .IsUnique();

                    b.ToTable("capture_proxy_addrs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.CaptureUserCa", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DiscordId")
                        .HasColumnType("text")
                        .HasColumnName("discord_id");

                    b.Property<byte[]>("Pfx")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("pfx");

                    b.Property<string>("Thumbprint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("thumbprint");

                    b.HasKey("UserId");

                    b.ToTable("capture_user_cas");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ContractRelease", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ContractId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("contract_id");

                    b.Property<bool>("CoopAllowed")
                        .HasColumnType("boolean")
                        .HasColumnName("coop_allowed");

                    b.Property<string>("CustomEggId")
                        .HasColumnType("text")
                        .HasColumnName("custom_egg_id");

                    b.Property<int>("Egg")
                        .HasColumnType("integer")
                        .HasColumnName("egg");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTimeOffset?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<bool>("Leggacy")
                        .HasColumnType("boolean")
                        .HasColumnName("leggacy");

                    b.Property<double>("LengthSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("length_seconds");

                    b.Property<int>("MaxCoopSize")
                        .HasColumnType("integer")
                        .HasColumnName("max_coop_size");

                    b.Property<double>("MinutesPerToken")
                        .HasColumnType("double precision")
                        .HasColumnName("minutes_per_token");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<int>("ProphecyEggs")
                        .HasColumnType("integer")
                        .HasColumnName("prophecy_eggs");

                    b.Property<byte[]>("Proto")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("proto");

                    b.Property<string>("SeasonId")
                        .HasColumnType("text")
                        .HasColumnName("season_id");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<bool>("UltraOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("ultra_only");

                    b.HasKey("Id");

                    b.HasIndex("ContractId");

                    b.HasIndex("StartTime");

                    b.HasIndex("ContractId", "StartTime")
                        .IsUnique();

                    b.ToTable("contract_releases");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ContributedCapture", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("client_version");

                    b.Property<Guid>("ContributorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("contributor_user_id");

                    b.Property<string>("DedupeHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedupe_hash");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'");

                    b.Property<DateTimeOffset>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("recorded_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset?>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("Kind");

                    b.HasIndex("ContributorUserId", "DedupeHash")
                        .IsUnique();

                    b.HasIndex("ContributorUserId", "Status");

                    b.HasIndex("Status", "RecordedAt");

                    b.ToTable("contributed_captures");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Device", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("CapturePort")
                        .HasColumnType("integer")
                        .HasColumnName("capture_port");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("Enabled")
                        .HasColumnType("boolean")
                        .HasColumnName("enabled");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("runtime")
                        .HasColumnName("origin");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target");

                    b.HasKey("Id");

                    b.ToTable("devices");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DeviceAsset", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("SourceVersion")
                        .HasColumnType("text")
                        .HasColumnName("source_version");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("Platform", "Kind", "Name")
                        .IsUnique();

                    b.ToTable("device_assets");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DeviceJob", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<int?>("ClientVersion")
                        .HasColumnType("integer")
                        .HasColumnName("client_version");

                    b.Property<string>("Detail")
                        .HasColumnType("jsonb")
                        .HasColumnName("detail");

                    b.Property<string>("DeviceId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Message")
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<string>("Outcome")
                        .HasColumnType("text")
                        .HasColumnName("outcome");

                    b.Property<bool?>("Reachable")
                        .HasColumnType("boolean")
                        .HasColumnName("reachable");

                    b.Property<string>("Revision")
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("DeviceId", "Id");

                    b.HasIndex("DeviceId", "Kind", "Id");

                    b.ToTable("device_jobs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DeviceJobLine", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("At")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("at")
                        .HasDefaultValueSql("now()");

                    b.Property<long?>("Bytes")
                        .HasColumnType("bigint")
                        .HasColumnName("bytes");

                    b.Property<string>("Entry")
                        .HasColumnType("text")
                        .HasColumnName("entry");

                    b.Property<long>("JobId")
                        .HasColumnType("bigint")
                        .HasColumnName("job_id");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("level");

                    b.Property<string>("Sha256")
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("text");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "Id");

                    b.ToTable("device_job_lines");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DeviceState", b =>
                {
                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<int?>("ClientVersion")
                        .HasColumnType("integer")
                        .HasColumnName("client_version");

                    b.Property<bool>("Dirty")
                        .HasColumnType("boolean")
                        .HasColumnName("dirty");

                    b.Property<string>("HarvestedRevision")
                        .HasColumnType("text")
                        .HasColumnName("harvested_revision");

                    b.Property<bool>("Harvesting")
                        .HasColumnType("boolean")
                        .HasColumnName("harvesting");

                    b.Property<DateTimeOffset?>("LastHarvestAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_harvest_at");

                    b.Property<string>("LastHarvestNote")
                        .HasColumnType("text")
                        .HasColumnName("last_harvest_note");

                    b.Property<string>("LastHarvestStatus")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_harvest_status");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Revision")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("revision");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("DeviceId");

                    b.ToTable("device_state");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Doc", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyMd")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("body_md");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKind", "SubjectKey")
                        .IsUnique();

                    b.ToTable("docs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DocImage", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("ByteSize")
                        .HasColumnType("integer")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.HasKey("Id");

                    b.ToTable("doc_images");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.EnvDesign", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("env_designs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.EnvDesignVersion", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<Guid?>("AuthorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("author_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<long>("DesignId")
                        .HasColumnType("bigint")
                        .HasColumnName("design_id");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<int?>("RolledBackFrom")
                        .HasColumnType("integer")
                        .HasColumnName("rolled_back_from");

                    b.Property<int>("VersionNo")
                        .HasColumnType("integer")
                        .HasColumnName("version_no");

                    b.HasKey("Id");

                    b.HasIndex("DesignId", "VersionNo")
                        .IsUnique();

                    b.ToTable("env_design_versions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ExtractJob", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "AppVersion")
                        .IsUnique();

                    b.ToTable("extract_jobs");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.FeedDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("attempted_at");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("dedup_key");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("proto_build")
                        .HasColumnName("event_kind");

                    b.Property<int?>("ResponseCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_code");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "EventKind", "DedupKey")
                        .IsUnique();

                    b.ToTable("feed_deliveries");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.FeedSubscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("proto_build")
                        .HasColumnName("event_kind");

                    b.Property<int>("FailCount")
                        .HasColumnType("integer")
                        .HasColumnName("fail_count");

                    b.PrimitiveCollection<string[]>("Filters")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text[]")
                        .HasColumnName("filters")
                        .HasDefaultValueSql("'{}'");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<string>("Label")
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastDeliveryAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_delivery_at");

                    b.Property<string>("MessageTemplate")
                        .HasColumnType("text")
                        .HasColumnName("message_template");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.PrimitiveCollection<string[]>("Platforms")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("platforms");

                    b.Property<string>("Secret")
                        .HasColumnType("text")
                        .HasColumnName("secret");

                    b.Property<string>("TargetUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("target_url");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("trigger");

                    b.HasKey("Id");

                    b.ToTable("feed_subscriptions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.FeedSuppression", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dedup_key");

                    b.Property<string>("EventKind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("proto_build")
                        .HasColumnName("event_kind");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("reason");

                    b.Property<int>("SubscriptionId")
                        .HasColumnType("integer")
                        .HasColumnName("subscription_id");

                    b.Property<string>("Summary")
                        .HasColumnType("text")
                        .HasColumnName("summary");

                    b.HasKey("Id");

                    b.HasIndex("SubscriptionId", "CreatedAt");

                    b.ToTable("feed_suppressions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.GameDataDocument", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("InputSha")
                        .HasColumnType("text")
                        .HasColumnName("input_sha");

                    b.Property<string>("Json")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("json");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.ToTable("game_data_documents");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.GameEvent", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("EventId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_id");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("event_type");

                    b.Property<DateTimeOffset?>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message");

                    b.Property<double>("Multiplier")
                        .HasColumnType("double precision")
                        .HasColumnName("multiplier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<bool>("Ultra")
                        .HasColumnType("boolean")
                        .HasColumnName("ultra");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("StartTime");

                    b.HasIndex("EventType", "StartTime");

                    b.ToTable("game_events");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ImageBuild", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset?>("FinishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finished_at");

                    b.Property<string>("Log")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("log");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("Spec")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("spec");

                    b.Property<DateTimeOffset>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.Property<string>("Tag")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tag");

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.HasIndex("Tag");

                    b.ToTable("image_builds");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.KnownVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Changelog")
                        .HasColumnType("text")
                        .HasColumnName("changelog");

                    b.Property<DateTimeOffset>("FirstSeen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset?>("ReleaseDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("release_date");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "AppVersion", "Source")
                        .IsUnique();

                    b.ToTable("known_versions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.PeriodicalsSnapshot", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_json");

                    b.Property<string>("Sha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha");

                    b.HasKey("Id");

                    b.HasIndex("CapturedAt");

                    b.HasIndex("Sha")
                        .IsUnique();

                    b.ToTable("periodicals_snapshots");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ProtoCanonical", b =>
                {
                    b.Property<string>("ProtoSha")
                        .HasColumnType("text")
                        .HasColumnName("proto_sha");

                    b.Property<string>("CanonicalSha")
                        .HasColumnType("text")
                        .HasColumnName("canonical_sha");

                    b.Property<string>("CanonicalText")
                        .HasColumnType("text")
                        .HasColumnName("canonical_text");

                    b.Property<DateTimeOffset>("ComputedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("computed_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<bool>("Ok")
                        .HasColumnType("boolean")
                        .HasColumnName("ok");

                    b.HasKey("ProtoSha");

                    b.ToTable("proto_canonicals");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ProtoProto", b =>
                {
                    b.Property<int>("ProtoVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("proto_version_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ProtoVersionId"));

                    b.Property<string>("MessageIndex")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("message_index");

                    b.Property<string>("ProtoText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_text");

                    b.HasKey("ProtoVersionId");

                    b.ToTable("proto_protos");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ProtoShaOrder", b =>
                {
                    b.Property<string>("ProtoSha")
                        .HasColumnType("text")
                        .HasColumnName("proto_sha");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("ProtoSha");

                    b.ToTable("proto_sha_orders");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ProtoVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApkRef")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apk_ref");

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<int?>("CanonicalId")
                        .HasColumnType("integer")
                        .HasColumnName("canonical_id");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("client_version");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DetectedBy")
                        .HasColumnType("text")
                        .HasColumnName("detected_by");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("ProtoSha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_sha");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Platform", "Build")
                        .IsUnique();

                    b.ToTable("proto_versions");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.ProvisionedInstanceRow", b =>
                {
                    b.Property<string>("InstanceId")
                        .HasColumnType("text")
                        .HasColumnName("instance_id");

                    b.Property<string>("AdbSerial")
                        .HasColumnType("text")
                        .HasColumnName("adb_serial");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("DeviceId")
                        .HasColumnType("text")
                        .HasColumnName("device_id");

                    b.Property<string>("HostRef")
                        .HasColumnType("text")
                        .HasColumnName("host_ref");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("image");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state");

                    b.HasKey("InstanceId");

                    b.HasIndex("DeviceId");

                    b.HasIndex("State");

                    b.ToTable("provisioned_instances");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.RouteBinaryCatalog", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("BinaryVersion")
                        .HasColumnType("text")
                        .HasColumnName("binary_version");

                    b.Property<string>("Method")
                        .HasColumnType("text")
                        .HasColumnName("method");

                    b.Property<string>("Platform")
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("RefreshedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refreshed_at");

                    b.Property<string>("RequestType")
                        .HasColumnType("text")
                        .HasColumnName("request_type");

                    b.Property<bool>("RequestWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("request_wrapped");

                    b.Property<string>("ResponseType")
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<bool>("ResponseWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("response_wrapped");

                    b.HasKey("Path");

                    b.ToTable("route_binary_catalog");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.RouteOverride", b =>
                {
                    b.Property<string>("Path")
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<bool?>("PathParam")
                        .HasColumnType("boolean")
                        .HasColumnName("path_param");

                    b.Property<string>("RequestType")
                        .HasColumnType("text")
                        .HasColumnName("request_type");

                    b.Property<bool?>("RequestWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("request_wrapped");

                    b.Property<string>("ResponseType")
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<bool?>("ResponseWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("response_wrapped");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Path");

                    b.ToTable("route_overrides");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.SiteThemePolicy", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<bool>("CustomCssEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("custom_css_enabled");

                    b.Property<long?>("DefaultThemeId")
                        .HasColumnType("bigint")
                        .HasColumnName("default_theme_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UpdatedByUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by_user_id");

                    b.HasKey("Id");

                    b.ToTable("site_theme_policy");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StagedProto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AppVersion")
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<string>("ClientVersion")
                        .HasColumnType("text")
                        .HasColumnName("client_version");

                    b.Property<string>("Confidence")
                        .HasColumnType("text")
                        .HasColumnName("confidence");

                    b.Property<string>("MessageIndex")
                        .HasColumnType("text")
                        .HasColumnName("message_index");

                    b.Property<string>("OriginCommit")
                        .HasColumnType("text")
                        .HasColumnName("origin_commit");

                    b.Property<DateTimeOffset?>("OriginDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("origin_date");

                    b.Property<string>("OriginRepo")
                        .HasColumnType("text")
                        .HasColumnName("origin_repo");

                    b.Property<string>("Package")
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("ProtoSha")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_sha");

                    b.Property<string>("ProtoText")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("proto_text");

                    b.Property<string>("ReviewNote")
                        .HasColumnType("text")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("SubmittedBy")
                        .HasColumnType("text")
                        .HasColumnName("submitted_by");

                    b.HasKey("Id");

                    b.HasIndex("ProtoSha");

                    b.HasIndex("Status");

                    b.ToTable("staged_protos");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredApk", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<string>("Build")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("build");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("CapturedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("captured_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Package")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("package");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("SourceDeviceId")
                        .HasColumnType("text")
                        .HasColumnName("source_device_id");

                    b.Property<string>("Split")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("split");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("Platform", "Package", "Build");

                    b.HasIndex("Platform", "Package", "AppVersion", "Build", "Split")
                        .IsUnique();

                    b.ToTable("stored_apks");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredBinary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<int>("EffectiveSymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("effective_symbol_count");

                    b.Property<int>("NativeSymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("native_symbol_count");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<DateTimeOffset>("PulledAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("pulled_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("Platform", "AppVersion")
                        .IsUnique();

                    b.ToTable("stored_binaries");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredEndpoint", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Eid")
                        .HasColumnType("text")
                        .HasColumnName("eid");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<string>("ResponseJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_json");

                    b.Property<string>("ResponseType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Path", "Eid")
                        .IsUnique();

                    b.ToTable("stored_endpoints");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredModule", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.Property<string>("Version")
                        .HasColumnType("text")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Sha256");

                    b.ToTable("device_modules");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.StoredRoute", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("path");

                    b.Property<bool>("PathParam")
                        .HasColumnType("boolean")
                        .HasColumnName("path_param");

                    b.Property<bool>("PathParamOnly")
                        .HasColumnType("boolean")
                        .HasColumnName("path_param_only");

                    b.Property<string>("RawResponse")
                        .HasColumnType("text")
                        .HasColumnName("raw_response");

                    b.Property<string>("RequestType")
                        .HasColumnType("text")
                        .HasColumnName("request_type");

                    b.Property<bool>("RequestWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("request_wrapped");

                    b.Property<string>("ResponseType")
                        .HasColumnType("text")
                        .HasColumnName("response_type");

                    b.Property<bool>("ResponseWrapped")
                        .HasColumnType("boolean")
                        .HasColumnName("response_wrapped");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("source");

                    b.HasKey("Id");

                    b.HasIndex("Path")
                        .IsUnique();

                    b.HasIndex("Source");

                    b.ToTable("stored_routes");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.SubjectTag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("SubjectKey")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_key");

                    b.Property<string>("SubjectKind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subject_kind");

                    b.Property<long>("TagId")
                        .HasColumnType("bigint")
                        .HasColumnName("tag_id");

                    b.HasKey("Id");

                    b.HasIndex("SubjectKind", "SubjectKey", "TagId")
                        .IsUnique();

                    b.ToTable("subject_tags");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.SymbolizedBinary", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("AppVersion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("app_version");

                    b.Property<long>("ByteSize")
                        .HasColumnType("bigint")
                        .HasColumnName("byte_size");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("bytes");

                    b.Property<string>("Platform")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("platform");

                    b.Property<string>("Sha256")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sha256");

                    b.Property<int>("SymbolCount")
                        .HasColumnType("integer")
                        .HasColumnName("symbol_count");

                    b.Property<DateTimeOffset>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("uploaded_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("Id");

                    b.HasIndex("Sha256");

                    b.HasIndex("Platform", "AppVersion")
                        .IsUnique();

                    b.ToTable("symbolized_binaries");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.Tag", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text")
                        .HasColumnName("color");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("tags");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.UserTheme", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("model");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("integer")
                        .HasColumnName("schema_version");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("Validation")
                        .HasColumnType("jsonb")
                        .HasColumnName("validation");

                    b.HasKey("Id");

                    b.HasIndex("OwnerUserId");

                    b.HasIndex("OwnerUserId", "Slug")
                        .IsUnique();

                    b.HasIndex(new[] { "OwnerUserId" }, "ix_user_themes_owner_active")
                        .IsUnique()
                        .HasFilter("is_active");

                    b.ToTable("user_themes");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("text");

                    b.Property<string>("Xml")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("EggIncognito.Data.Models.DeviceJobLine", b =>
                {
                    b.HasOne("EggIncognito.Data.Models.DeviceJob", null)
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EggIncognito.Data.Models.EnvDesignVersion", b =>
                {
                    b.HasOne("EggIncognito.Data.Models.EnvDesign", null)
                        .WithMany()
                        .HasForeignKey("DesignId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
