<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AngleSharp" />
    <PackageReference Include="bunit" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\EggIncognito.csproj" />
    <ProjectReference Include="..\..\EggIncognito.RouteGenerator\EggIncognito.RouteGenerator.csproj" />
    <ProjectReference Include="..\..\EggIncognito.RelayAgent\EggIncognito.RelayAgent.csproj" />
  </ItemGroup>

</Project>
