<Project>
  <PropertyGroup>
    <EnableSingleFileAnalyzer Condition="('$(CI)' == 'true' Or '$(PublishSingleFile)' == 'true') And !$(MSBuildProjectName.EndsWith('.Tests')) And $([MSBuild]::IsTargetFrameworkCompatible('$(TargetFramework)', 'net8.0'))">true</EnableSingleFileAnalyzer>
  </PropertyGroup>
</Project>
