<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="AngleSharp" Version="1.5.2" />
    <PackageVersion Include="bunit" Version="2.7.2" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="EggIdentity.AdminUi" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Bot" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Bot.AdminUi" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Client" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.CodeStyle" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Deploy" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Deploy.AdminUi" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Fallback" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Metrics" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Metrics.AdminUi" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Settings" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Settings.AdminUi" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Settings.Store" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.Styles" Version="2.3.4" />
    <PackageVersion Include="EggIdentity.UI" Version="2.3.4" />
    <PackageVersion Include="Gee.External.Capstone" Version="2.3.0" />
    <PackageVersion Include="Google.Protobuf" Version="3.29.3" />
    <PackageVersion Include="Grpc.Tools" Version="2.71.0" />
    <PackageVersion Include="Microsoft.AspNetCore.DataProtection.EntityFrameworkCore" Version="10.0.10" />
    <PackageVersion Include="Microsoft.AspNetCore.Mvc.Testing" Version="10.0.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.Analyzers" Version="3.11.0" />
    <PackageVersion Include="Microsoft.CodeAnalysis.CSharp" Version="4.14.0" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10" />
    <PackageVersion Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Hosting.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Http" Version="10.0.10" />
    <PackageVersion Include="Microsoft.Extensions.Logging.Abstractions" Version="10.0.10" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="MinVer" Version="7.0.0" />
    <PackageVersion Include="MonorailCss" Version="0.1.3" />
    <PackageVersion Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.2" />
    <PackageVersion Include="SharpCompress" Version="0.50.4" />
    <PackageVersion Include="SharpGLTF.Toolkit" Version="1.0.6" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.12" />
    <PackageVersion Include="SixLabors.ImageSharp.Drawing" Version="2.1.7" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>
</Project>
